### ISSUE TITLE
no compila

### ISSUE THREAD

**Issue by edwardes2201** [zijiechenrobotics/ig_lio#18]
[ 37%] Building CXX object ig_lio/CMakeFiles/ig_lio_node.dir/src/pointcloud_preprocess.cpp.o
[ 37%] Building CXX object ig_lio/CMakeFiles/ig_lio_node.dir/src/lio.cpp.o
[ 37%] Building CXX object ig_lio/CMakeFiles/ig_lio_node.dir/src/faster_voxel_grid.cpp.o
[ 50%] Building CXX object ig_lio/CMakeFiles/ig_lio_node.dir/src/ig_lio_node.cpp.o
[ 62%] Building CXX object ig_lio/CMakeFiles/ig_lio_node.dir/src/voxel_map.cpp.o
[ 75%] Building CXX object ig_lio/CMakeFiles/ig_lio_node.dir/src/SymmetricEigenSolver.cpp.o
[ 87%] Building CXX object ig_lio/CMakeFiles/ig_lio_node.dir/src/timer.cpp.o
In file included from /home/edu/ig_lio/catkin_ws/src/ig_lio/src/voxel_map.cpp:1:0:
/home/edu/ig_lio/catkin_ws/src/ig_lio/include/ig_lio/voxel_map.h:10:10: fatal error: execution: No existe el archivo o el directorio
 #include <execution>
          ^~~~~~~~~~~
compilation terminated.
ig_lio/CMakeFiles/ig_lio_node.dir/build.make:117: fallo en las instrucciones para el objetivo 'ig_lio/CMakeFiles/ig_lio_node.dir/src/voxel_map.cpp.o'
make[2]: *** [ig_lio/CMakeFiles/ig_lio_node.dir/src/voxel_map.cpp.o] Error 1
make[2]: *** Se espera a que terminen otras tareas....
In file included from /home/edu/ig_lio/catkin_ws/src/ig_lio/include/ig_lio/lio.h:30:0,
                 from /home/edu/ig_lio/catkin_ws/src/ig_lio/src/lio.cpp:1:
/home/edu/ig_lio/catkin_ws/src/ig_lio/include/ig_lio/voxel_map.h:10:10: fatal error: execution: No existe el archivo o el directorio
 #include <execution>
          ^~~~~~~~~~~
compilation terminated.
ig_lio/CMakeFiles/ig_lio_node.dir/build.make:103: fallo en las instrucciones para el objetivo 'ig_lio/CMakeFiles/ig_lio_node.dir/src/lio.cpp.o'
make[2]: *** [ig_lio/CMakeFiles/ig_lio_node.dir/src/lio.cpp.o] Error 1
In file included from /home/edu/ig_lio/catkin_ws/src/ig_lio/include/ig_lio/lio.h:30:0,
                 from /home/edu/ig_lio/catkin_ws/src/ig_lio/src/ig_lio_node.cpp:16:
/home/edu/ig_lio/catkin_ws/src/ig_lio/include/ig_lio/voxel_map.h:10:10: fatal error: execution: No existe el archivo o el directorio
 #include <execution>
          ^~~~~~~~~~~
compilation terminated.
ig_lio/CMakeFiles/ig_lio_node.dir/build.make:75: fallo en las instrucciones para el objetivo 'ig_lio/CMakeFiles/ig_lio_node.dir/src/ig_lio_node.cpp.o'
make[2]: *** [ig_lio/CMakeFiles/ig_lio_node.dir/src/ig_lio_node.cpp.o] Error 1
/home/edu/ig_lio/catkin_ws/src/ig_lio/src/pointcloud_preprocess.cpp: In member function ‘void PointCloudPreprocess::ProcessVelodyne(const ConstPtr&, pcl::PointCloud<pcl::PointXYZINormal>::Ptr&)’:
/home/edu/ig_lio/catkin_ws/src/ig_lio/src/pointcloud_preprocess.cpp:70:12: warning: variable ‘yaw_end’ set but not used [-Wunused-but-set-variable]
     double yaw_end = yaw_first;
            ^~~~~~~
CMakeFiles/Makefile2:2628: fallo en las instrucciones para el objetivo 'ig_lio/CMakeFiles/ig_lio_node.dir/all'
make[1]: *** [ig_lio/CMakeFiles/ig_lio_node.dir/all] Error 2
Makefile:145: fallo en las instrucciones para el objetivo 'all'
make: *** [all] Error 2
Invoking "make -j8 -l8" failed
edu@edu-APB20:~/ig_lio/catkin_ws$

**Comment by zijiechenrobotics** [comment]
Sorry, I can't find a solution to this problem in your log message :sweat:
I recommend you to use docker to solve this problem, https://github.com/zijiechenrobotics/ig_lio_workspace

**Comment by edwardes2201** [comment]
HELLO FRIEND, I MANAGED TO COMPILE ON UBUNTU 20.04, EVERYTHING WENT WELL, I AM TESTING IT WITH LIVOX MID360. BUT THE MAP IS NOT SAVED IN PCD AT COMPLETION, IS THERE ANY WAY TO SAVE THE GENERATED MAP? GREETINGS.
